version: '3.8'

services:
  postgres:
    image: postgres:15.2
    restart: always
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data

  pg_admin:
    container_name: pgAdmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: vasyldubno@gmail.com
      PGADMIN_DEFAULT_PASSWORD: vasyldubno
    ports:
      - 5050:80

  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./server/src:/usr/src/app/src

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    restart: always
    volumes:
      - ./client/src:/usr/src/app/src